spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  security:
    user:
      name: wfc
      password: 111
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true